from __future__ import annotations

"""
Additional v9 plots:
- outcome distributions across Monte Carlo runs (baseline + interventions)
- CDF for offload and risk proxy
- Pareto-style scatter (risk vs ED within4) with scenario labels

Inputs come from outputs/v8/tables (generated by scripts/run_v8_all.py).
"""

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def _save(fig: plt.Figure, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(fig)


def plot_distributions(df: pd.DataFrame, outdir: Path, tag: str) -> None:
    # Histograms
    for col in ["rr_2030", "offload_2030", "within4_2030", "effshare_effective_2030"]:
        if col not in df.columns:
            continue
        fig = plt.figure()
        plt.hist(df[col].dropna(), bins=30)
        plt.title(f"{tag}: distribution of {col}")
        plt.xlabel(col)
        plt.ylabel("count")
        _save(fig, outdir / f"dist_{tag}_{col}.png")

    # CDF
    for col in ["rr_2030", "offload_2030"]:
        if col not in df.columns:
            continue
        s = df[col].dropna().sort_values().reset_index(drop=True)
        y = (s.index + 1) / len(s)
        fig = plt.figure()
        plt.plot(s, y)
        plt.title(f"{tag}: CDF of {col}")
        plt.xlabel(col)
        plt.ylabel("CDF")
        _save(fig, outdir / f"cdf_{tag}_{col}.png")


def plot_pareto(table: pd.DataFrame, outdir: Path) -> None:
    # risk vs within4
    fig = plt.figure()
    x = table["rr_2030"]
    y = table["within4_2030"]
    plt.scatter(x, y)
    for _, r in table.iterrows():
        plt.text(float(r["rr_2030"]), float(r["within4_2030"]), str(r["scenario"]), fontsize=8)
    plt.title("Scenario trade-off: risk proxy vs ED≤4h (2030)")
    plt.xlabel("rr_2030 (relative risk proxy)")
    plt.ylabel("within4_2030 (share)")
    _save(fig, outdir / "pareto_rr_vs_within4_2030.png")


def main() -> None:
    repo = Path(__file__).resolve().parents[1]
    outdir = repo / "outputs" / "v9" / "plots"
    outdir.mkdir(parents=True, exist_ok=True)

    # If v8 produced MC samples, plot them; otherwise fall back to scenario table only.
    mc_path = repo / "outputs" / "v8" / "tables" / "mc_samples.csv"
    if mc_path.exists():
        mc = pd.read_csv(mc_path)
        plot_distributions(mc, outdir, tag="mc")

    scenario_path = repo / "outputs" / "v8" / "tables" / "scenario_table.csv"
    if scenario_path.exists():
        sc = pd.read_csv(scenario_path)
        # ensure standard columns exist
        if "harm_2030" in sc.columns and "rr_2030" not in sc.columns:
            sc["rr_2030"] = sc["harm_2030"]
        plot_pareto(sc.rename(columns={
            "harm_2030": "rr_2030",
            "within4_2030": "within4_2030",
        }), outdir)

    print(f"Wrote plots to: {outdir}")

if __name__ == "__main__":
    main()
